### ISSUE TITLE
crash when adding new document whilst offline

### ISSUE THREAD

**Issue by SogoGolf** [Azure/Azure.Android#85]
## Bug Information
add a new document whilst device is offline (Galaxy S5; Android 6.0.1)

### Steps to Reproduce
used following code:
```
            val document = ClubDocument()  
            document.name = "NEW CLUB"

            AzureData.createDocument (document, "sogocollection", "sogodb") {
                // created document = it.resource
                if (it.response != null && it.response?.isSuccessful!!) {
                    lastAddedId = it.resource?.id!!
                    runOnUiThread {
                        textView.text = "success creating a new club. ${it.jsonData}"
                    }
                } else {
                    Log.i("AZURE", "ERROR: create document failed. ${it.jsonData}")
                    runOnUiThread {
                        textView.text = "ERROR: ${it.jsonData}"
                    }
                }

            }

```

### Expected Behavior
app caches the added document and does not crash

### Actual Behavior
app crash

error message:
```
02-10 21:35:54.122 8897-9119/? E/AndroidRuntime: FATAL EXCEPTION: OkHttp Dispatcher
    Process: com.sogo.cosmostest2, PID: 8897
    java.lang.NoSuchMethodError: No interface method getOrDefault(Ljava/lang/Object;Ljava/lang/Object;)Ljava/lang/Object; in class Ljava/util/Map; or its super classes (declaration of 'java.util.Map' appears in /system/framework/core-libart.jar)
        at com.azure.data.util.ResourceOracle.getSelfLink(ResourceOracle.kt:258)
        at com.azure.data.service.ResourceWriteOperationQueue.createOrReplaceOffline(ResourceWriteOperationQueue.kt:225)
        at com.azure.data.service.ResourceWriteOperationQueue.addCreateOrReplace(ResourceWriteOperationQueue.kt:54)
        at com.azure.data.service.DocumentClient.processCreateOrReplaceResponse(DocumentClient.kt:1281)
        at com.azure.data.service.DocumentClient.access$processCreateOrReplaceResponse(DocumentClient.kt:35)
        at com.azure.data.service.DocumentClient$createOrReplace$$inlined$createRequest$lambda$3.onFailure(DocumentClient.kt:1421)
        at okhttp3.RealCall$AsyncCall.execute(RealCall.java:215)
        at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
        at java.lang.Thread.run(Thread.java:818)

```

**Comment by SogoGolf** [comment]
updating to 0.1.2 fixed the crash
